### ISSUE TITLE
    import telegram

### ISSUE THREAD

**Issue by efaria** [fronbasal/unifi-voucherbot#1]
line 1, in <module>
    import telegram
ModuleNotFoundError: No module named 'telegram'

**Comment by fronbasal** [comment]
You have to install the required packages first. 

You can either use the recommended package manager, [Pipenv](https://pipenv.pypa.io/en/latest/), thus following the instructions in the readme (note: you have to execute the script _inside_ the virtualenv, you can enter it by running `pipenv shell`) or by manually installing [unifipy](https://pypi.org/project/unifipy/) and [python-telegram-bot](https://github.com/python-telegram-bot/python-telegram-bot).
